export default {
  APISTATUS: "APISTATUS",
  GET_VIDEO_DETAILS: "GET_VIDEO_DETAILS",
  FETCH_TRANSCRIPT: "FETCH_TRANSCRIPT",
  GET_SUPPORTED_LANGUAGES: "GET_SUPPORTED_LANGUAGES",
  GENERATE_TRANSCRIPT: "GENERATE_TRANSCRIPT",
  SAVE_TRANSCRIPT: "SAVE_TRANSCRIPT",
};
  